# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  #- 5.4
services:
  - mongodb
  - redis-server # --port 7777

## optionally specify a list of environments, for example to test different RDBMS
env:
   - DB=mongo
   #- DB=mysql

# now, all services will be started and env will be set
## execute any number of scripts before the test run, custom env's are available as variables
# Clone project repository from GitHub
# cd to clone directory
# Checkout commit for this build
# and than go to steps
# step 1
before_install:
   - echo "before_install"
   - ls -l /etc/init.d/
   - cat /etc/init.d/redis-server
   - cat /etc/init.d/mongodb
   - which mongod
   - which redis-server
   - ls -l /home/travis/
   - pwd

# step 2
install:
   - echo "install"
   - ls -l /home/travis/build/
   - ls -l /home/travis/builds/
   - pstree

# step 3
before_script:
   - echo "before_script"
   - ls -l /home/travis/build/pinguo-liuzhaohui/
   - ls -l
   - pstree
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

## omitting "script:" will default to phpunit
## use the $DB env variable to determine the phpunit.xml to use
#script: phpunit --configuration phpunit_$DB.xml --coverage-text
# step 4
script: phpunit --coverage-text test/

# step 5
finish:
  - echo "finish"

# step 6 on success
after_success:
  - echo "after_success"
  - ls -l

# step 6 on failure
after_failure:
  - echo "after_failure"

# step 7
after_script:
  - echo "after_script"
  - pstree
  - pwd
  - cat /home/travis/state.log
  - ls -l
## configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#travis"
